# Generated by Django 2.2.7 on 2022-03-26 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Address_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Address'),
        ),
        migrations.AddField(
            model_name='donor',
            name='Donor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationrequestformresult',
            name='Donor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Donor.Donor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Donor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Donor.Donor'),
        ),
    ]
