# Generated by Django 2.2.7 on 2022-04-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_auto_20220326_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequestformresult',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
