# Generated by Django 2.2.7 on 2022-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_donationrequestformresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='status',
            field=models.CharField(blank=True, default='in progress', max_length=10, null=True),
        ),
    ]
