# Generated by Django 2.2.7 on 2022-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0004_auto_20220403_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='ProfilePic',
            field=models.FileField(blank=True, default='profilepic/userdefault.png', null=True, upload_to='profilepic/'),
        ),
    ]
