# Generated by Django 2.2.7 on 2022-04-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0005_donor_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='in progress', max_length=10, null=True),
        ),
    ]
