# Generated by Django 2.2.7 on 2022-04-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0006_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestformquesitons',
            name='HeartDisease',
            field=models.TextField(blank=True, null=True),
        ),
    ]
