# Generated by Django 4.0.3 on 2022-04-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0010_auto_20220403_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequestformquesitons',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
