# Generated by Django 4.0.3 on 2022-04-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0011_donationrequestformquesitons_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequestformquesitons',
            old_name='type',
            new_name='Type',
        ),
    ]
