# Generated by Django 4.0.3 on 2022-04-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donor', '0012_rename_type_donationrequestformquesitons_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Abortion',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='BloodHealthfulnessInfo',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='BreastFeeding',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Donor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='HeartDisease',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Kidney_Lung_Bloodpressure_Diabetes_Epilepsy',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Liverproblems',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Preagnant',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='STD',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='SeriousSkinRepair',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Slpet_Unsafely_OtherThanPartner',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Tattoo_Ear_skin_pierced_lastmonth',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
    ]
