# Generated by Django 4.0.3 on 2022-04-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0013_alter_donationrequestformresult_abortion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Donor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Donor.donor'),
        ),
    ]
