# Generated by Django 4.0.3 on 2022-04-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0014_alter_donationrequestformresult_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='Donor_id',
        ),
    ]
