# Generated by Django 2.2.7 on 2022-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
