# Generated by Django 2.2.7 on 2022-04-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_auto_20220326_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profilePic',
            field=models.ImageField(blank=True, default='profilepic/userdefault.png', null=True, upload_to='profilepic/'),
        ),
    ]
