# Generated by Django 2.2.7 on 2022-04-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_userregistration_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='profilePic',
            new_name='ProfilePic',
        ),
    ]
