# Generated by Django 2.2.7 on 2022-04-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0005_auto_20220402_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='ProfilePic',
            field=models.FileField(blank=True, default='profilepic/userdefault.png', null=True, upload_to='profilepic/'),
        ),
    ]
