# Generated by Django 2.2.7 on 2022-03-26 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('Camps_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('CampsName', models.CharField(max_length=10)),
                ('CampsWoreda', models.CharField(max_length=50)),
                ('CampsKebele', models.IntegerField()),
                ('CampsPlace', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=10)),
                ('EventDate', models.DateField(max_length=20)),
                ('EventPlace', models.CharField(max_length=50)),
                ('EventTime', models.TimeField()),
                ('Eventtype', models.CharField(max_length=10)),
            ],
        ),
    ]
