# Generated by Django 2.2.7 on 2022-03-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20220331_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
