# Generated by Django 2.2.7 on 2022-03-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20220331_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Eventtype',
            new_name='EventType',
        ),
    ]
