# Generated by Django 2.2.7 on 2022-03-26 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('Blood_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('BloodGroup', models.CharField(max_length=20)),
                ('PackNo', models.CharField(max_length=20)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('ExpDate', models.DateTimeField(max_length=10)),
                ('QuantityOfBlood', models.CharField(max_length=4)),
            ],
        ),
    ]
