# Generated by Django 2.2.7 on 2022-03-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blood', '0001_initial'),
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='Donor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Donor.Donor'),
        ),
    ]
