# Generated by Django 2.2.7 on 2022-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
